CREATE TABLE LogPengguna
(
    IdL INT IDENTITY (1,1) PRIMARY KEY
)

CREATE TABLE Tower
(
    IdT INT IDENTITY (1,1) PRIMARY KEY,
	nama VARCHAR(50)
)

CREATE TABLE [Role]
(
    IdR INT IDENTITY (1,1) PRIMARY KEY,
	tipe VARCHAR(30)
)

CREATE TABLE [User] 
(
	NIK CHAR(16) PRIMARY KEY,
	nama VARCHAR(100),
	alamatDomisili VARCHAR(100),
	noTelp CHAR(12),
	OTP CHAR(6)
)

CREATE TABLE RoleUser
(
	NIK CHAR(16) FOREIGN KEY REFERENCES [User] (NIK),
	IdR INT FOREIGN KEY REFERENCES Role (IdR)
)

CREATE TABLE Sarusun
(
	IdS INT IDENTITY(1,1) PRIMARY KEY,
	Lantai VARCHAR(30),
	penggunaanAirH INT,
	penggunaanAirB INT,
	penggunaanAirT INT,
	nikPemilik CHAR(16) FOREIGN KEY REFERENCES [User] (NIK),
	IdT INT FOREIGN KEY REFERENCES Tower (IdT)
)

CREATE TABLE Perangkat
(
	noSerial CHAR(16) PRIMARY KEY,
	statusAir BIT,
	IdS INT FOREIGN KEY REFERENCES Sarusun (IdS)
)

CREATE TABLE Pengelola
(
	IdT INT FOREIGN KEY REFERENCES Tower (IdT),
	nikPengelola CHAR(16) FOREIGN KEY REFERENCES [User] (NIK)
)

CREATE TABLE logMonitorAir
(
	IdL INT FOREIGN KEY REFERENCES LogPengguna (IdL),
	NIK CHAR(16) FOREIGN KEY REFERENCES [User] (NIK),
	IdS INT FOREIGN KEY REFERENCES Sarusun (IdS),
	waktu DATETIME
)

CREATE TABLE aktivasiPerangkat
(
	IdL INT FOREIGN KEY REFERENCES LogPengguna (IdL),
	NIK CHAR(16) FOREIGN KEY REFERENCES [User] (NIK),
	IdS INT FOREIGN KEY REFERENCES Sarusun (IdS),
	waktu DATETIME
)